### PR TITLE
Give this a full refresh (libraries, php version, code style, tests)

### PR DESCRIPTION
**Pull request by okaufmann**
Hi,

As I'm using this library in some of my products I detected it's not compatible with Laravel 7.
After got my hands on it, I decided to give this a whole refresh.

This is what I did:
- Updated all libraries to the latest versions
- Dropped Laravel version older than 7 (cause innovation ftw …💁‍♂️)
- Restructure the tests into its own namespaces
- Make tests compatible with sqlite

If you want these changes I suggest to release a new major release...

### CODE REVIEW

**Comment by okaufmann** [comment]
Any ideas how to set the version of phpunit to make it work with all testes php versions?

**Comment by okaufmann** [comment]
I finally got time to fix the tests and also convert them to be run as github actions.

**Comment by okaufmann** [comment]
you can check build status on my forks actions page: https://github.com/okaufmann/teamwork/actions

**Comment by necenzurat** [comment]
Hey, awesome job, quick question, can you make it a composer package since this version is abandonware?

And if anyone is wondering how to use this version, you can do this in your composer.json file
```json
"repositories": [{
    "type": "vcs",
    "url": "https://github.com/okaufmann/teamwork"
}],
"require": {
    "php": "^7.2",
    "mpociot/teamwork": "dev-master",
}
````

**Comment by necenzurat** [comment]
@mpociot can you publish a new release?

**Comment by okaufmann** [comment]
I'll do as soon I have checked everything working ✌️

**Pull request merged**
