### PR TITLE
Add validation of name and email

### PR DESCRIPTION
**Pull request by Jeroen-G**
This PR adds a request validation to the controller stubs for the name and email entered by the user when creating a team or an invite.

### CODE REVIEW

**Comment by okaufmann** [comment]
Would you like to resolve the conflicts? I caused them by changing some things. Sorry about that :/

**Comment by Jeroen-G** [comment]
@okaufmann I can't because I have deleted my fork :/

**Comment by okaufmann** [comment]
Ok, then I'll take your changes right in a commit. Thanks :)

**Comment by okaufmann** [comment]
It's now included https://github.com/mpociot/teamwork/commit/fee391ad7392d647b84fee54f14a0743671d5e13

Thanks again!

**Pull request closed without merging**
