### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected a dependency for the `laravel/framework`. Unless you have a special requirement for depending on the entire Laravel framework, it's recommended to add dependencies for the specific `illuminate` packages instead.

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/mpociot/teamwork/pull/158/commits/1dbb12541a19c37bd88d743877b32edbc2cd4a5d?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/teamwork.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "mpociot/teamwork": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by mbardelmeijer** [comment]
@okaufmann could you take a look at this PR to add Laravel 11 support to this package? Thanks! 🙏

**Comment by siarheipashkevich** [comment]
@okaufmann please take a look at this PR, thanks.

**Comment by mmccaff** [comment]
@okaufmann @mpociot please merge this when you can. I did some basic testing using the package from Shift's `"dev-l11-compatibility"` branch on Laravel 10 and didn't see any issues, and all tests for L8..L11 in CI are passing. Thank you! 🙏 

Update: I also tested with Laravel 11, and haven't ran into any issues.

**Comment by siarheipashkevich** [comment]
@okaufmann @mpociot please take a look at this PR.

**Comment by flymia** [comment]
I second this. I would love to use this package under Laravel 11.

**Comment by recluzegeek** [comment]
> @okaufmann @mpociot please merge this when you can. I did some basic testing using the package from Shift's `"dev-l11-compatibility"` branch on Laravel 10 and didn't see any issues, and all tests for L8..L11 in CI are passing. Thank you! 🙏
> 
> Update: I also tested with Laravel 11, and haven't ran into any issues.

I've been using it with Laravel 11 for about two weeks now, and everything seems to be working perfectly fine without any issues.

**Comment by neerajsohal** [comment]
Please merge this! I too have tested it with L11. It works without issues.

**Pull request merged**
