### PR TITLE
Added Laravel 6 Support

### PR DESCRIPTION
**Pull request by oliuz**

### CODE REVIEW

**Comment by andrewminion-luminfire** [comment]
Any chance of this being incorporated soon? I’d love to use it with a Laravel 6.0 project I’m starting!

**Comment by webong** [comment]
@mpociot this patch has been pending for a while now ... I'd love if it can get merged soon, really need this package for a project I am working on.

 Thanks.

**Comment by oliverbj** [comment]
Any news on this request? Would also love getting support for a 6.0 Laravel project I am working on.

**Comment by mpociot** [comment]
Sorry for the long delay :)

**Pull request merged**
