### PR TITLE
Updated owner() method with the correct relationship (#100 continued)

### LINKED ISSUE #99: TeamworkTeamTrait owner() method should be a BelongsTo relationship
Currently the relationship of the `Team` model is using the incorrect join.

The `owner()` relationship on the `Team` model should be a `belongsTo()` relationship as the `Team` model has the `owner_id` column.

The original code does work but with implementation of Laravel Nova it becomes an issue as they require a `BelongsTo` join to properly function.

https://github.com/mpociot/teamwork/blob/4de34f53c44757030ed54dde5f69fe48b7a207e1/src/Mpociot/Teamwork/Traits/TeamworkTeamTrait.php#L35-L46

### PR DESCRIPTION
**Pull request by oliverpool**
Apparently the PR #100 (trying to fix #99) didn't work out.
This is a new attempt :-)

---

TeamworkTeamTrait::owner() method now returns a \Illuminate\Database\Eloquent\Relations\BelongsTo to be inline with current standards on relationships

### CODE REVIEW

**Comment by oliverpool** [comment]
This would be a breaking change for someone using the `owner()` method and expecting a `HasOne` object.

But this corrects the semantic (since a Team actually belongs to an Owner) and should be transparent for people using the `owner` property.

**Comment by oliverpool** [comment]
(@spriggsey did most of the work)

**Comment by zagreusinoz** [comment]
Given that this and a number of other PRs haven't been dealt with, I'm wondering if this package should be considered abandoned?  I have switched to the fork that @oliuz has made, however there are still a few inconsistencies in some of the relations (e.g. ownedTeams does not return a relation while teams does).

I'm just wondering where to drop pull requests to make suggested changes...

**Comment by okaufmann** [comment]
I'll close this PR due to conflicts and as it does also change the required laravel version (would have this in a separate PR).

As this is a Bug I considered your changes in this commit https://github.com/mpociot/teamwork/commit/63098fba618b57824f2525c624f9fab91395eb6.

**Pull request closed without merging**
